#  https://docs.docker.com/compose/compose-file/build/
#  https://squash.io/tutorial-host-network-in-docker-compose/

services:
  # DO NOT REMOVE THIS COMMENT https://github.com/sukesh-ak/setup-mosquitto-with-docker?tab=readme-ov-file
  # mqtt5 eclipse-mosquitto
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./infrastructure/MqttBroker/config:/mosquitto/config:rw
      - ./infrastructure/MqttBroker/data:/mosquitto/data:rw
      - ./infrastructure/MqttBroker/log:/mosquitto/log:rw
    restart: unless-stopped

# reverse proxy
  nginx:
    build:
      context: ./infrastructure/ReverseProxy
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - ui
    ports:
      - 80:80
      - 443:443
#      - 9002:9002
#      - 1884:1884
    volumes:
     - ./infrastructure/ReverseProxy/conf.d:/etc/nginx/conf.d/:rw,cached
     - ./infrastructure/ReverseProxy/nginx.conf:/etc/nginx/nginx.conf:rw,cached
     - ./infrastructure/ReverseProxy/certs:/etc/nginx/certs
     - ./infrastructure/ReverseProxy/data:/data

  # ui app node.js
  ui:
    container_name: ui
    build:
      context: ./apps/client
      target: prod
    restart: unless-stopped
    depends_on:
      - mqtt
    ports:
      - 3000:3000
    volumes:
      - ./apps/client:/app:rw,cached
    env_file:
      - ./env.d/production/.env_ui

# server app node.js
  server:
    container_name: server
    build:
      context: ./apps/server
      target: prod
    depends_on:
      - mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./apps/server:/app:rw,cached
      - /sys:/sys
      - /dev:/dev
    env_file:
      - ./env.d/production/.env_server

networks:
 default:
